name: Node.js Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install -g yarn
      - name: yarn install, build, and test
        working-directory: ./src/web-client
        run: |
          yarn install
          yarn run build
          yarn test --passWithNoTests
      - name: Publish to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: wesleydebruijn/orlog/web-client
          registry: docker.pkg.github.com
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: src/web-client/Dockerfile
          tags: latest
